### ISSUE TITLE
_encode_check_unknown is not supported in the most recent version of sklearn

### ISSUE THREAD

**Issue by as6520** [prijatelj/exputils#1]
[Labels.py](https://github.com/prijatelj/exputils/blob/d2be1655d8d2194bcfabf96556760205166beb60/exputils/data/labels.py) in the exp utils package uses the internal function _encode_check_unknown which is not present in the most recent version of scikit learn. Since the requirements.txt only specifies the lower bound of the version for scikit learn, pip installing the package causes `ImportError`.

**Comment by prijatelj** [comment]
This dependency has been removed in version '0.1.3', which is what master currently is synced with and is also captured in the branch `v0.1`. Pypi package has been updated to this recent version. Thanks.

**Comment by as6520** [comment]
Thanks for the update!

**Comment by prijatelj** [comment]
**make that version 0.1.4, cuz i made a mistake and it needed corrected.
